### PR TITLE
SDK changes to enable the getting and setting the time in the RTC

### PR DESCRIPTION
**Pull request by brentward**

### CODE REVIEW

**Comment by rumbledethumps** [comment]
Making sure you're aware of the C standard library for time, which CC65 does support...
https://github.com/cc65/cc65/blob/master/include/time.h

**Comment by brentward** [comment]
I'll modify the sdk changes to implement the c functions and use included structs in time instead of creating a new one.

**Comment by rumbledethumps** [comment]
When you make a pull request, every subsequent push sends me a notification I can't unsubscribe from without unsubscribing from the whole project. Pull requests are for when everything is done and ready for a review and merge. It takes 10 seconds to make a new pull request, so I'm closing all these.

**Comment by brentward** [comment]
Is there a way to request feedback on changes that aren't ready for merge?

**Comment by rumbledethumps** [comment]
You're asking for review early because you jumped directly to coding. Sometimes this is fine. Other times it's ok or necessary to document as you code. But when you're feeling overwhelmed, it's because you started coding before sufficiently defining the problem. Please read this:

https://docs.kernel.org/process/3.Early-stage.html

I've had the video system in RFC for over two months now. I haven't written any code for it. The existing video system is the hardware validation code and will not survive its successor. 90% of my time has been spent not-coding. This isn't do as I say, this is do as I do. And what everyone else who works on kernels and compilers has to do.

**Pull request closed without merging**
